# Generated by Django 4.0.4 on 2022-05-15 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_buyurtma', models.CharField(max_length=200)),
                ('body_buyurtma', models.TextField()),
                ('summary_buyurtma', models.CharField(max_length=200)),
                ('price_buyurtma', models.PositiveIntegerField()),
                ('muddat', models.DateField()),
                ('telefon_raqam', models.CharField(max_length=50, null=True)),
                ('aloqa_uchun_email_manzil', models.EmailField(max_length=100, null=True)),
                ('room_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('telegram', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtmabajarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_nomer', models.CharField(max_length=20)),
                ('buyurtmachi_name', models.CharField(max_length=20)),
                ('tg_user', models.CharField(max_length=30)),
                ('taklif', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtmachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(max_length=100)),
                ('gmail', models.EmailField(max_length=254)),
                ('parol', models.CharField(max_length=20)),
                ('shahar', models.CharField(max_length=150)),
                ('manzil', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Firmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('yonalish', models.CharField(max_length=200)),
                ('litsenzya', models.ImageField(upload_to='images/')),
                ('ishchi_soni', models.PositiveIntegerField()),
                ('portfolio', models.ImageField(upload_to='images/')),
                ('logotip', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('room', models.CharField(max_length=1000000)),
                ('user', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Mutaxasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('familya', models.CharField(max_length=150)),
                ('otasining_ismi', models.CharField(max_length=150)),
                ('rasm', models.ImageField(upload_to='images/')),
                ('tugilgan_sana', models.DateField()),
                ('shahar', models.CharField(max_length=150)),
                ('manzil', models.CharField(max_length=150)),
                ('telefon', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('lavozim', models.TextField()),
                ('yonalish', models.TextField()),
                ('maosh', models.PositiveIntegerField()),
                ('portfolio', models.ImageField(upload_to='images/')),
                ('sertifikat', models.ImageField(upload_to='images/')),
                ('til', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('summery', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
