# Generated by Django 4.0.4 on 2022-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutaxasis',
            name='lavozim',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='mutaxasis',
            name='yonalish',
            field=models.CharField(max_length=550),
        ),
    ]
